### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by marsjupiter1** [gordonb3/tuyapp#1]
I have done a couple of things.

1. Compiled the code as is on Ubuntu 21.10
2. ported the code to esp32

In both cases when I try and connect to two devices I have been controlling successfully over the socket on the ubuntu machine in some node.js code. I get an immediate "connection reset by peer" error from Ubuntu. 
Notably on the esp32 I was also getting "connection reset by peer" then I moved the connect to just before the write and it claims to have done the write but will read nothing.
The esp32 code can though talk to a dummy server that just echos back what is sent.
In passing, I do believe there is a bug:

write(m_sockfd, buffer, size + sizeof(MESSAGE_SEND_HEADER) + sizeof(MESSAGE_SEND_TRAILER));

should I think be:

write(m_sockfd, buffer, size );

as you have already accounted for the extra bits. But it makes no difference to the outcome.

regards

Martin Walker

**Comment by gordonb3** [comment]
Hi,

Thanks for pointing that out. That is indeed a remnant of an earlier communication test. I removed the trailing bytes in the network communication and the resulting code still allows me to control my devices.

Unsure about your setup. Instant connection reset appears to hint that the device already has an active connection - for some reason tuya does not allow multiple connections, e.g. one for monitoring usage and the other one for control. You should also note that the current code only supports the latest protocol version so it should be expected to fail with older devices. I do have something of a clue how to communicate with older devices, but as I don't own any I'm hesitant of publishing such code.

**Comment by marsjupiter1** [comment]
I have just tried another device and to my amazement it worked. So I think possibly I just got very unlucky with devices with old firmware. Though that still seems weird.
thanks for the reply.

**Comment by gordonb3** [comment]
Did you try to enable debug?

```
cmake -B examples -Sexamples -DENABLE_DEBUG=1
make
```

This will print hex dumps of the (encrypted) messages sent and returned.

**Comment by marsjupiter1** [comment]
Hi,
Just a heads up. I have created:

https://github.com/marsjupiter1/ArduinoTuya/blob/main/README.md

and of course given you credit.
It's a complete and utter mess at the moment, but is communicating with
both 3.3 and 3.1 devices.
I aim to tidy it up. I guess you may have a problem testing if you don't
have a 3.1 device. It occurs to me I have a spare, and could post.

regards

Martin

**Comment by gordonb3** [comment]
Good job. The 3.1 code looks pretty much like I expected.

Should you be interested, this is the implementation where I created the library for:
https://github.com/gordonb3/oikomaticz/tree/master/src/hardware/LocalTuya

As part of a home automation project this aims to constantly monitor the devices which goes well for tracking energy use (or generation in the case of my plugin PV) but I found that if the device is in the `off` state it can sometimes drop the connection which is a state that the protocol does not allow you to detect - i.e. there is no ACK to either `heartbeat` or `updatedps`.

**Comment by marsjupiter1** [comment]
I'm soldiering on for the moment, but finding from an esp32 device that 3.1
is very unreliable and 3.3 not near reliable enough for what I need.
Just ordered some tasmota plus which seem a better bet from many
perspectives.

regards

Martin
